version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: filerun_root_passwd
      MYSQL_USER: filerun_user
      MYSQL_PASSWORD: filerun_user_passwd
      MYSQL_DATABASE: filerun_db
    volumes:
      - /filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun_db
      FR_DB_USER: filerun_user
      FR_DB_PASS: filerun_user_passwd
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8003:80"
    volumes:
      - /filerun/html:/var/www/html
      - /filerun/user-files:/user-files